# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
X = torch.rand(7, 7)
X, X.shape


(tensor([[0.0485, 0.7925, 0.8969, 0.7990, 0.5970, 0.5296, 0.9520],
         [0.8191, 0.1593, 0.1562, 0.6903, 0.9081, 0.6329, 0.4115],
         [0.1992, 0.1398, 0.9636, 0.6775, 0.1753, 0.9841, 0.9198],
         [0.8132, 0.4993, 0.1724, 0.5991, 0.0397, 0.1936, 0.5041],
         [0.3965, 0.1629, 0.5800, 0.0612, 0.1763, 0.0331, 0.6698],
         [0.8272, 0.1276, 0.4872, 0.1774, 0.2587, 0.6245, 0.2993],
         [0.1072, 0.5518, 0.4048, 0.8796, 0.2872, 0.0172, 0.7167]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
Y = t2 = torch.rand(1, 7)
# Perform matrix multiplication
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[2.1405],
         [2.2912],
         [1.8170],
         [1.5288],
         [1.1968],
         [1.6619],
         [1.2866]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
import torch
torch.manual_seed(0)
# if we add this before each random tensor all "random tensors" would be equal

# Create two random tensors
X = torch.rand(7, 7)
Y = torch.rand(1, 7)

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape


(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
import torch
torch.cuda.manual_seed(1)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
X = torch.rand(2, 3).to(device)
Y = torch.rand(2, 3).to(device)
X, Y


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
Z = torch.matmul(X, Y.T)
Z, Z.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
max = torch.max(Z)

# Find min
min = torch.min(Z)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
maxIndex = Z.argmax()

# Find arg min
minIndex = Z.argmin()
maxIndex, minIndex



tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
X = torch.rand(1,1,1,10)

# Remove single dimensions
Y = X.squeeze()

# Print out tensors and their shapes
X, X.shape, Y, Y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))