In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # single number no dimensions

0

In [4]:
scalar.item() # retrieves int from tensor

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim # 2 dimensions

2

In [9]:
MATRIX.shape # number of items in each dimension

torch.Size([2, 2])

In [10]:
MATRIX[0] # first dimension

tensor([7, 8])

In [11]:
# Tensor
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
    ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim # 0 dim -> contains 1 item which is parent brackets
# 1 dim -> contains 3 items which is 3 brackets with 2 commas seperating
# 2 dim -> contains 3 items which is 3 items in each bracket 2 commas seperating

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR5dim = torch.tensor(
    [
    [
    [
    [
    [1,2,3,4,5],
    [4,5,6,7,8],
    [7,8,9,10,11]
    ]
                             ]
                            ]
                           ]
                          )
TENSOR5dim.ndim

5

In [15]:
TENSOR5dim.shape

torch.Size([1, 1, 1, 3, 5])

In [16]:
# Vector 1 dimensional tensor
# Scalar 0 dimensional tensor
# MATRIX 2 dimensional tensor
# Tensor any dimensions, so all Vector, scalar, and Matrix are tensors

In [17]:
# Random Tensors
random_tensor = torch.rand(3, 224,224)
random_tensor

tensor([[[0.9362, 0.6197, 0.5071,  ..., 0.9578, 0.4127, 0.1459],
         [0.3371, 0.1692, 0.9418,  ..., 0.8963, 0.0241, 0.5004],
         [0.0513, 0.0285, 0.3721,  ..., 0.3316, 0.8323, 0.3153],
         ...,
         [0.7667, 0.0436, 0.1706,  ..., 0.9426, 0.8984, 0.9490],
         [0.5999, 0.5636, 0.9315,  ..., 0.3081, 0.2848, 0.6812],
         [0.1589, 0.1780, 0.3482,  ..., 0.3490, 0.8405, 0.2062]],

        [[0.5469, 0.4957, 0.8363,  ..., 0.3085, 0.2591, 0.6163],
         [0.9299, 0.4114, 0.1537,  ..., 0.6878, 0.1782, 0.0995],
         [0.2264, 0.1196, 0.4903,  ..., 0.0675, 0.4756, 0.1507],
         ...,
         [0.8375, 0.2136, 0.7939,  ..., 0.3920, 0.2414, 0.6301],
         [0.4508, 0.2525, 0.4716,  ..., 0.6454, 0.5824, 0.9183],
         [0.3823, 0.1530, 0.6084,  ..., 0.4354, 0.8323, 0.7847]],

        [[0.0357, 0.7373, 0.5975,  ..., 0.0014, 0.0117, 0.9328],
         [0.6615, 0.6823, 0.3017,  ..., 0.9086, 0.6851, 0.8323],
         [0.5657, 0.3023, 0.0748,  ..., 0.4800, 0.8072, 0.

In [18]:
one_to_ten = torch.arange(1,12, 2)
one_to_ten

tensor([ 1,  3,  5,  7,  9, 11])

In [19]:
copyzeros = torch.zeros_like(input = one_to_ten)
copyzeros

tensor([0, 0, 0, 0, 0, 0])

In [20]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # what data type is the tensor
                               device=None, # What device tensor is on "cuda" on gpu
                               requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_16_tensor.dtype
float32 = float_16_tensor.type(torch.float32)
float32.dtype
float16 = float32.type(torch.float16)
float16.dtype

torch.float16

In [24]:
float16 * float32 # works although different data types but some operations will give error
# when not in proper type

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [26]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [27]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5892, 0.5543, 0.6872, 0.9906],
        [0.1131, 0.1998, 0.7598, 0.0922],
        [0.0726, 0.3189, 0.7910, 0.2190]])

In [28]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5892, 0.5543, 0.6872, 0.9906],
        [0.1131, 0.1998, 0.7598, 0.0922],
        [0.0726, 0.3189, 0.7910, 0.2190]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [29]:
my_tensor = torch.rand(6,2, dtype=torch.float64, device="cpu")
print(my_tensor.shape)
print(my_tensor.dtype)
my_tensor.device

torch.Size([6, 2])
torch.float64


device(type='cpu')

In [30]:
my_tensor.to("cpu")
my_tensor.device
my_tensor = my_tensor.to(torch.float32)
my_tensor.reshape(3,4)

tensor([[0.9771, 0.4729, 0.6241, 0.9871],
        [0.2700, 0.9124, 0.2388, 0.6623],
        [0.8202, 0.4214, 0.8924, 0.0869]])

In [31]:
my_tensor.dtype

torch.float32

In [32]:
my_tensor.device

device(type='cpu')

In [33]:
my_tensor.to("cpu")
my_tensor.device

device(type='cpu')

In [34]:
my_tensor.device

device(type='cpu')

In [35]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [38]:
# Matrix multiplication (dot product)
tensor1 = torch.tensor([[1,2],[4,5]])
tensor2 = torch.tensor([[2,2],[2,2]])

In [39]:
print("matrix mult dot product")
print(tensor1, "*", tensor2)
print(f"Equals: {torch.matmul(tensor1, tensor2)}")

matrix mult dot product
tensor([[1, 2],
        [4, 5]]) * tensor([[2, 2],
        [2, 2]])
Equals: tensor([[ 6,  6],
        [18, 18]])


In [40]:
# manual matrix mult without torch.matmul
%%time
val = 0
for i in range(len(tensor1)):
  val += tensor1[i] * tensor2[i]
print(val)

tensor([10, 14])
CPU times: user 1.24 ms, sys: 1.03 ms, total: 2.27 ms
Wall time: 5.07 ms


In [41]:
%%time
torch.matmul(tensor1, tensor2)

CPU times: user 32 µs, sys: 4 µs, total: 36 µs
Wall time: 39.8 µs


tensor([[ 6,  6],
        [18, 18]])

In [42]:
# Rules for matrix mult
# inner dimensions must be equal
# result is the outer dimensions
t1  = torch.rand(3,2)
t2 = torch.rand(2,3)
print(t1)
print(t2)
torch.matmul(t1, t2)

tensor([[0.6974, 0.0462],
        [0.7908, 0.3392],
        [0.4646, 0.4252]])
tensor([[0.8465, 0.3536, 0.5856],
        [0.5386, 0.2453, 0.3058]])


tensor([[0.6153, 0.2579, 0.4226],
        [0.8521, 0.3628, 0.5668],
        [0.6223, 0.2686, 0.4021]])

In [43]:
t1 @ t2

tensor([[0.6153, 0.2579, 0.4226],
        [0.8521, 0.3628, 0.5668],
        [0.6223, 0.2686, 0.4021]])

In [44]:
# Shapes for matrix multiplicaton
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6],
                         [7,8]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# tensor_A @ tensor_B gives error different dims

tensor_B = tensor_B.T
print(f"Tensor B: {tensor_B}")
res = tensor_A @ tensor_B
res.shape
torch.matmul(tensor_A, tensor_B)

Tensor B: tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117],
        [129, 144, 159]])

In [45]:
# to fix dimensions issue of inner dims not matching we can use
# transpose which switches columns and rows of a matrix like above

In [46]:
torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117],
        [129, 144, 159]])

In [67]:
# Finding the min, max, mea, and sum etc (Tensor aggregation)
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [48]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [49]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [50]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [51]:
# torch mean doesnt work on int64 needs a float
# int64 is long
# make float or complex

In [52]:
# Biggest issues is shape inner in matrix mult and wrong data types

In [53]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [54]:
maxindex = torch.argmax(x)
maxindex
minindex = torch.argmin(x)
print(f"The min index is at: {minindex}")
print(f"The max index is at: {maxindex}")

The min index is at: 0
The max index is at: 9


In [55]:
x[maxindex]

tensor(90)

In [56]:
## Reshaping stacking squeezing and unsqueezing tensors

'''Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeesze - removes all 1 dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target sensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way'''

"Reshaping - reshapes an input tensor to a defined shape\n* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor\n* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)\n* Squeesze - removes all 1 dimensions from a tensor\n* Unsqueeze - add a '1' dimension to a target sensor\n* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way"

In [57]:
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [58]:
torch.rand(2,9)

tensor([[0.0479, 0.1806, 0.0371, 0.3058, 0.4442, 0.9545, 0.8153, 0.6240, 0.0062],
        [0.7166, 0.3775, 0.0992, 0.7692, 0.5021, 0.8602, 0.7330, 0.9087, 0.5785]])

In [59]:
torch.reshape(x, (1,9)) # adds 1 dimension

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [60]:
# if we try doing reshape 2,9 then tries to fit the 9 elements we have in the 1 dimensional vector
# into 2 rows and 9 columns

In [61]:
torch.reshape(x, (9,1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [62]:
y = torch.arange(1., 11.) # shape is 10
zzz = torch.reshape(y, (5,2)) # so 5*2 = 10 so reshaping allowed
zzz

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [69]:
y

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [68]:
zzz.ndim, zzz.shape

(2, torch.Size([5, 2]))

In [64]:
x2 = torch.arange(0., 12.)
x2, x2.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 torch.Size([12]))

In [65]:
torch.reshape(x2, (3,4))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [66]:
torch.reshape(x2, (4,3))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [71]:
x3 = torch.arange(1., 10.)
x3, x3.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [83]:
z = x3.view(1,9) # view shares memory with original tensor (z same memory as x)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [86]:
# the view here will make z a 2d tensor
x, z

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [73]:
# Changing z (view of x) will change x
z[0] = 2
z

tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [78]:
x3

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [82]:
x3 = torch.arange(1., 10.)
x3, x3.shape, x3.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [91]:
z[: , 0] = 2 # select all elements along that dimension, all rows
z[0][1] = 3
z, x3

(tensor([[2., 3., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([2., 3., 3., 4., 5., 6., 7., 8., 9.]))

In [95]:
# Stack tensors on top of each other
x_stacked1 = torch.stack([x,x,x,x,x], dim=1)
x_stacked0 = torch.stack([x,x,x,x,x], dim=0)
x_stacked1, x_stacked0
# only 2 dimensions so doesnt work to stack at dim = 2 which is third
# when stacking at dimension 0, adds more of the same tensor x
# when stacking at dimension 1, inside of tensor x then stack the same number the amount of times specified


(tensor([[ 0,  0,  0,  0,  0],
         [10, 10, 10, 10, 10],
         [20, 20, 20, 20, 20],
         [30, 30, 30, 30, 30],
         [40, 40, 40, 40, 40],
         [50, 50, 50, 50, 50],
         [60, 60, 60, 60, 60],
         [70, 70, 70, 70, 70],
         [80, 80, 80, 80, 80],
         [90, 90, 90, 90, 90]]),
 tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]))

In [102]:
print(torch.squeeze(x)) # removes dimensions that are 1 with squeeze
print(torch.unsqueeze(x, dim=0)) # undoes what it squeezed


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])


In [119]:
ex = torch.zeros(2,1,2,1)
print(ex, ex.shape) #2 arrays 1 array 2 arrays 1el
exsqu = torch.squeeze(ex)
print(exsqu,exsqu.shape)

tensor([[[[0.],
          [0.]]],


        [[[0.],
          [0.]]]]) torch.Size([2, 1, 2, 1])
tensor([[0., 0.],
        [0., 0.]]) torch.Size([2, 2])


In [120]:
exunsq = torch.unsqueeze(exsqu, dim=1)
print(exunsq, exunsq.shape)
exunsqq = torch.unsqueeze(exunsq, dim=3)
print(exunsqq, exunsqq.shape)

tensor([[[0., 0.]],

        [[0., 0.]]]) torch.Size([2, 1, 2])
tensor([[[[0.],
          [0.]]],


        [[[0.],
          [0.]]]]) torch.Size([2, 1, 2, 1])


In [121]:
# torch.permute returns original tensor with dimensions permuted (changed)
x_orig = torch.rand(size=(224,224,3))
print(f"The original is {x_orig.shape}")
x_permuted = x_orig.permute(2,0,1)
print(f"The permuted is {x_permuted.shape}")


The original is torch.Size([224, 224, 3])
The permuted is torch.Size([3, 224, 224])


In [134]:
# permuted tensor shares same memory with original
print(x_permuted)
x_permuted[0,0,0]

tensor([[[0.9100, 0.5619, 0.8914,  ..., 0.3276, 0.3366, 0.6090],
         [0.0291, 0.9002, 0.6074,  ..., 0.6286, 0.7274, 0.1986],
         [0.3329, 0.0441, 0.5455,  ..., 0.9066, 0.6026, 0.9165],
         ...,
         [0.9979, 0.7850, 0.2716,  ..., 0.7690, 0.7828, 0.2033],
         [0.9561, 0.0840, 0.3996,  ..., 0.9060, 0.4212, 0.0691],
         [0.4397, 0.1328, 0.8769,  ..., 0.1328, 0.7190, 0.6135]],

        [[0.0636, 0.8136, 0.0608,  ..., 0.8791, 0.2029, 0.0396],
         [0.2009, 0.8771, 0.6796,  ..., 0.3512, 0.8454, 0.3165],
         [0.3628, 0.1842, 0.2531,  ..., 0.4597, 0.4544, 0.6642],
         ...,
         [0.8696, 0.8007, 0.2799,  ..., 0.0734, 0.6519, 0.4633],
         [0.1120, 0.8976, 0.2954,  ..., 0.6660, 0.8688, 0.9732],
         [0.5307, 0.5458, 0.4996,  ..., 0.2480, 0.5894, 0.5939]],

        [[0.2929, 0.3082, 0.4491,  ..., 0.6413, 0.3125, 0.6284],
         [0.0249, 0.3584, 0.9677,  ..., 0.3727, 0.9901, 0.8377],
         [0.2066, 0.6941, 0.4135,  ..., 0.9316, 0.5859, 0.

tensor(0.9100)

In [135]:
x_permuted[0][0][0] = 10
x_orig[0][0][0]

tensor(10.)

In [2]:
# Indexing selecting data from tensors similar to indexing with numpy
import torch
import numpy as np
x = torch.arange(1,10).reshape(1,3,3)
x
x[0], x[0][1], x[0][1][2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(6))

In [3]:
x[:, 1, 1]

tensor([5])

In [19]:
# Numpy popular scientific numerical computing library
# Numpy array to tensor
array = np.arange(1, 8)
print(array, type(array), array.dtype)
tensorr = torch.from_numpy(array)
print(tensor, tensor.dtype)
# The default dtype for numpy is float 64 while for tensor its float 32

[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64
tensor([1, 2, 3, 4, 5, 6, 7]) torch.int64


In [20]:
tensorrr = torch.from_numpy(array).type(torch.float32)
tensorrr.dtype

torch.float32

In [21]:
# when converting from numpy -> pytorch default numpy type int64 or float 64 is used by pytorch unless specified

In [26]:
array
array[0] = 9
array, tensorrr
# tensor = torch.from_numpy(array) means the new tensor doesnt change if original np array changes

(array([9, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [27]:
# Tensor to numpy
tensor = torch.ones(8)
numpy_array = tensor.numpy()
tensor, numpy_array, tensor.dtype, numpy_array.dtype
# Same thing going from tensors to numpy, now numpy array will have default value of tensors float 32

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32,
 dtype('float32'))

In [28]:
tensor = tensor + 1
tensor, numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Again independent of chanegs when you change the tensor the new array wont be changed as well

In [29]:
## Pytorch reproducability (trying to take random out of random)

# How a nn learns, start with random numbers, tensor operations, update numbers to try and make them
# more accurate and better. Data -> again -> again -> again...
# to reduce the randomness in nns and pytorch comes to concept of random seed
# seed flavors the randomness

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A, random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4337, 0.3426, 0.5724, 0.2009],
        [0.2711, 0.1893, 0.0346, 0.7249],
        [0.9483, 0.5681, 0.3406, 0.6477]]) tensor([[0.8481, 0.9255, 0.7392, 0.4313],
        [0.4680, 0.0544, 0.8920, 0.5487],
        [0.8328, 0.1313, 0.0245, 0.2101]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [32]:
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # manual seed needs to be called with specified random seed before
# trying to make a random tensor to get same results in both random tensors (notr rlly random flavored)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) # same thing again
random_tensor_D = torch.rand(3,4)
print(random_tensor_C, random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [33]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [34]:
torch.cuda.device_count()

0

In [38]:
# putting models and tensors on the gpu (parallel computing multithreaded faster on gpu)
# train discover patterns quicker and more effecient with gpus

tensor = torch.tensor([1,2,3], device=device)
tensor.device



device(type='cpu')

In [ ]:
tensor_on_gpu = tensor.to("cuda") # works if gpu is available
tensor_on_gpu

In [ ]:
# numpy only works on CPU
# moving tensors back to cpu if we want to transform it to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu
gputensor = torch.from_numpy(tensor_back_on_cpu)
# tensor on gpu remains unchanged since we made a copy of the tensor onto the cpu and made it a numpyarray using .numpy()